#!/bin/bash

set -e

initfile=/etc/rundeck.init

chmod 1777 /tmp

if [[ -n "\${RUNDECK_GID}" && -n "\${RUNDECK_UID}" ]]; then
  echo "Setting rundeck account to \${RUNDECK_UID}:\${RUNDECK_GID}"
  groupmod -o -g \${RUNDECK_GID} rundeck
  usermod -o -u \${RUNDECK_UID} -g \${RUNDECK_GID} rundeck
  rm -rf /tmp/rundeck
fi

# chown directories and files that might be coming from volumes
chown -R mysql:mysql /var/lib/mysql
chown -R rundeck:rundeck /etc/rundeck
chown -R rundeck:rundeck /var/rundeck
chown -R rundeck:adm /var/log/rundeck
chown -R rundeck:rundeck /var/lib/rundeck
chown -R rundeck:rundeck /opt/rundeck-defaults


if [ ! -f "${initfile}" ]; then
   SERVER_URL=${SERVER_URL:-"https://0.0.0.0:4443"}
   SERVER_HOSTNAME=$(echo ${SERVER_URL} | awk -F/ '{print $3}' | awk -F: '{print $1}')
   SERVER_PROTO=$(echo ${SERVER_URL} | awk -F/ '{print $1}' | awk -F: '{print $1}')
   SERVER_PORT=$(echo ${SERVER_URL} | awk -F/ '{print $3}' | awk -F: '{print $2}')
   if [ -z ${SERVER_PORT} ]; then
      # No port in SERVER_URL so assume 443 for HTTPS or 80 otherwise
      if [ ${SERVER_PROTO} == "https" ]; then
         SERVER_PORT=443
      else
         SERVER_PORT=80
      fi
   fi
   DATABASE_URL=${DATABASE_URL:-"jdbc:mysql://localhost/rundeckdb?autoReconnect=true"}
   RUNDECK_PASSWORD=${RUNDECK_PASSWORD:-$(pwgen -s 15 1)}
   DEBIAN_SYS_MAINT_PASSWORD=${DEBIAN_SYS_MAINT_PASSWORD:-$(pwgen -s 15 1)}
   RUNDECK_STORAGE_PROVIDER=${RUNDECK_STORAGE_PROVIDER:-"file"}
   RUNDECK_PROJECT_STORAGE_TYPE=${RUNDECK_PROJECT_STORAGE_TYPE:-"file"}
   NO_LOCAL_MYSQL=${NO_LOCAL_MYSQL:-"false"}
   
update_user_password () {
   (
   echo "UPDATE mysql.user SET password=PASSWORD('${2}') WHERE user='${1}';"
   echo "FLUSH PRIVILEGES;"
   echo "quit"
   ) |
   mysql
}

   echo "=>Initializing rundeck - This may take a few minutes"
   if [ ! -f /var/lib/rundeck/.ssh/id_rsa ]; then
       echo "=>Generating rundeck key"
       sudo -u rundeck ssh-keygen -t rsa -b 4096 -f /var/lib/rundeck/.ssh/id_rsa -N ''
   fi
   
   if [ "$(ls -A /etc/rundeck)" ]; then
       echo "=>/etc/rundeck check OK"
   else
       echo "=>/etc/rundeck empty...setting up defaults"
       cp -R /opt/rundeck-defaults/* /etc/rundeck
       chown -R rundeck:rundeck /etc/rundeck
   fi

   if [ ! -f /etc/rundeck/ssl/truststore ]; then
       echo "=>Generating ssl cert"
       sudo -u rundeck keytool -keystore /etc/rundeck/ssl/keystore -alias rundeck -genkey -keyalg RSA -keypass adminadmin -storepass adminadmin -dname "cn=localhost, o=OME, c=DE" && \
       cp /etc/rundeck/ssl/keystore /etc/rundeck/ssl/truststore
   fi

   if [ "${NO_LOCAL_MYSQL}" == "false" ]; then
      echo "=>Initializing local MySQL..."
      if [ "$(ls -A /var/lib/mysql)" ]; then
         /etc/init.d/mysql start
      else
         echo "=>MySQL datadir is empty...initializing"
         /usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
         echo "=>Starting MySQL...ignore warning about debian-sys-maint user, it will be granted permissions momentarily"
         /etc/init.d/mysql start
         sleep 5
         (
         echo "GRANT ALL PRIVILEGES ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '${DEBIAN_SYS_MAINT_PASSWORD}';"
         echo "quit"
         ) |
         mysql
     fi
   
     # Set debian-sys-maint password
     update_user_password debian-sys-maint ${DEBIAN_SYS_MAINT_PASSWORD}
     sed -i 's,password\ \=\ .*,password\ \=\ '${DEBIAN_SYS_MAINT_PASSWORD}',g' /etc/mysql/debian.cnf

     (
     echo "CREATE DATABASE IF NOT EXISTS rundeckdb;"
     echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE, CREATE VIEW, ALTER, INDEX, EXECUTE ON rundeckdb.* TO 'rundeck'@'localhost' IDENTIFIED BY '${RUNDECK_PASSWORD}';"
     echo "quit"
     ) |
     mysql
     sleep 5
     /etc/init.d/mysql stop
     # Add MySQL to supervisord conf
     cat /opt/mysql.conf >> /etc/supervisor/conf.d/rundeck.conf
   else
      echo "=>NO_LOCAL_MYSQL set to true.  Skipping local MySQL setup"
   fi

   sed -i 's,grails.serverURL\=.*,grails.serverURL\='${SERVER_URL}',g' /etc/rundeck/rundeck-config.properties
   sed -i 's,dataSource.dbCreate.*,,g' /etc/rundeck/rundeck-config.properties
   sed -i 's,dataSource.url = .*,dataSource.url = '${DATABASE_URL}',g' /etc/rundeck/rundeck-config.properties
   if grep -q dataSource.username /etc/rundeck/rundeck-config.properties ; then
      : 
   else
      echo "dataSource.username = rundeck" >> /etc/rundeck/rundeck-config.properties
   fi
   if grep -q dataSource.password /etc/rundeck/rundeck-config.properties ; then
      sed -i 's,dataSource.password = .*,dataSource.password = '${RUNDECK_PASSWORD}',g' /etc/rundeck/rundeck-config.properties
   else
      echo "dataSource.password = ${RUNDECK_PASSWORD}" >> /etc/rundeck/rundeck-config.properties
   fi

   # framework.properties
   sed -i 's,framework.server.name\ \=.*,framework.server.name\ \=\ '${SERVER_HOSTNAME}',g' /etc/rundeck/framework.properties
   sed -i 's,framework.server.hostname\ \=.*,framework.server.hostname\ \=\ '${SERVER_HOSTNAME}',g' /etc/rundeck/framework.properties
   sed -i 's,framework.server.port\ \=.*,framework.server.port\ \=\ '${SERVER_PORT}',g' /etc/rundeck/framework.properties
   sed -i 's,framework.server.url\ \=.*,framework.server.url\ \=\ '${SERVER_URL}',g' /etc/rundeck/framework.properties

   if [ "${RUNDECK_STORAGE_PROVIDER}" == "db" ]; then
      echo "rundeck.storage.provider.1.type=db" >> /etc/rundeck/rundeck-config.properties
      echo "rundeck.storage.provider.1.path=/" >> /etc/rundeck/rundeck-config.properties
   fi

   if [ "${RUNDECK_PROJECT_STORAGE_TYPE}" == "db" ]; then
      echo "rundeck.projectsStorageType=db" >> /etc/rundeck/rundeck-config.properties
   fi
   # Plugins
   if ls /opt/rundeck-plugins/*.jar 1> /dev/null 2>&1; then
      echo "=>Installing plugins from /opt/rundeck-plugins"
      cp /opt/rundeck-plugins/*.jar /var/lib/rundeck/libext 2>/dev/null
   fi
   if ls /opt/rundeck-plugins/*.zip 1> /dev/null 2>&1; then
      echo "=>Installing plugins from /opt/rundeck-plugins"
      cp /opt/rundeck-plugins/*.zip /var/lib/rundeck/libext 2>/dev/null
   fi
   if ls /opt/rundeck-plugins/*.groovy 1> /dev/null 2>&1; then
      echo "=>Installing plugins from /opt/rundeck-plugins"
      cp /opt/rundeck-plugins/*.groovy /var/lib/rundeck/libext 2>/dev/null
   fi

echo -e "\n\n\n"
echo "==================================================================="
if [ "${NO_LOCAL_MYSQL}" == "true" ]; then
   echo "NO_LOCAL_MYSQL set to true so local MySQL has not been configured or started"
else
   echo "MySQL user 'root' has no password but only allows local connections"
fi
echo "MySQL user 'rundeck' password set to ${RUNDECK_PASSWORD}"
echo "Rundeck project storage type set to ${RUNDECK_PROJECT_STORAGE_TYPE}"
echo "Rundeck Storage provider set to ${RUNDECK_STORAGE_PROVIDER}"
echo "Rundeck public key:"
cat /var/lib/rundeck/.ssh/id_rsa.pub
echo "Server URL set to ${SERVER_URL}"
echo "==================================================================="

touch ${initfile}
fi

echo "Starting Supervisor.  You can safely CTRL-C and the container will continue to run with or without the -d (daemon) option"
/usr/bin/supervisord -c /etc/supervisor/conf.d/rundeck.conf >> /dev/null
