#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down mysql"
    /etc/init.d/mariadb stop
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting mysql"

/etc/init.d/mariadb start

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u mysql mariadb > /dev/null; do sleep 5; done
